all:
	${GORN_CXX} ${GORN_CXX_FLAGS} Crawler.cpp -o ${GORN_BIN}Crawler -I${GORN_UTILS} -lboost_thread -lboost_system -lpthread -lGL -lGLU -lglut;
	${GORN_CXX} ${GORN_CXX_FLAGS} DistributedCrawler.cpp -o ${GORN_BIN}DistributedCrawler -I${GORN_UTILS} -lboost_thread -lboost_system -lpthread -lGL -lGLU -lglut;
